export const sampleTexts = [
  "The quick brown fox jumps over the lazy dog while the sun rises in the horizon and birds sing melodious tunes filling the morning with joy and warmth for all.",
  "Coding is an art and a science, where each line of code adds value to the application while developers debug, refactor, and improve logic for performance and clarity.",
  "Learning new languages is exciting, opening doors to cultures, new friends, opportunities, and perspectives. Each word learned adds a bridge connecting minds across the globe with understanding.",
  "In the midst of challenges and failures, perseverance is key. Those who keep pushing forward, analyzing mistakes, and learning from them often achieve greatness in life and work.",
  "React and Node.js form a powerful duo for full stack development, enabling developers to create dynamic, responsive web applications with seamless frontend and robust backend integration.",
  "Every morning, people wake up with goals and dreams, planning their day with optimism, determination, and hope, striving to achieve tasks that bring satisfaction and progress.",
  "A typing race tests speed, accuracy, and concentration, challenging participants to focus on each keystroke while minimizing errors and improving their mental agility and reflexes during the challenge.",
  "JavaScript is versatile and widely used for web development, enabling interactive user interfaces, dynamic content, and smooth user experiences across websites and applications globally.",
  "The sun sets behind the mountains casting golden light over valleys, while rivers flow quietly, birds return to nests, and nature prepares for the calm and peaceful night ahead.",
  "Effective communication requires clarity, active listening, empathy, and thoughtful responses, fostering strong relationships and understanding in personal, professional, and social interactions worldwide.",
  "Consistency and discipline are often more valuable than bursts of effort. Daily incremental improvements compound over time, creating skills and results that are sustainable and impactful.",
  "A good leader inspires, listens, motivates, and guides the team while balancing vision with empathy, fostering trust, collaboration, and innovation among team members for success.",
  "The city wakes with a symphony of sounds, cars honking, people chatting, shops opening, and the aroma of coffee filling streets as life begins in vibrant rhythm.",
  "Traveling introduces individuals to diverse cultures, languages, foods, and landscapes, broadening minds, creating memories, and fostering appreciation for the richness and variety of the world around.",
  "Technology evolves rapidly, with new frameworks, tools, and paradigms emerging, demanding continuous learning, adaptation, and flexibility from developers who want to stay current and competitive.",
  "Books transport readers to different worlds, offering knowledge, inspiration, and entertainment, stimulating imagination, empathy, and critical thinking while nurturing a lifelong love for reading.",
  "Music evokes emotions, memories, and energy, providing comfort, motivation, and joy, connecting people across cultures and generations with its universal language and rhythms.",
  "Healthy habits such as exercise, balanced diet, and sufficient sleep improve physical, mental, and emotional well-being, enhancing focus, energy, and overall quality of life.",
  "Nature walks allow for reflection, stress relief, and appreciation of beauty, connecting humans to the environment and fostering mindfulness, calm, and mental clarity.",
  "Teamwork requires communication, trust, and cooperation, combining diverse skills to solve problems, achieve goals, and create results that surpass individual contributions.",
  "Innovation stems from curiosity, experimentation, and risk-taking, encouraging creative solutions, improvements, and breakthroughs that drive progress across technology, science, and human endeavors.",
  "Meditation and mindfulness practices help in reducing stress, improving focus, and enhancing emotional balance, cultivating awareness of the present moment and mental clarity.",
  "Historical events shape societies, cultures, and human behavior, teaching lessons, inspiring change, and providing context for understanding present and future challenges globally.",
  "Healthy competition motivates individuals to improve, push boundaries, and achieve personal bests while maintaining respect, fairness, and integrity throughout the process.",
  "Artistic expression allows people to convey thoughts, emotions, and ideas visually, musically, or through performance, connecting creators and audiences through shared experiences and interpretation.",
  "Gardening nurtures patience, responsibility, and appreciation for growth, as seeds transform into plants, flowers, and vegetables through consistent care, sunlight, and water.",
  "Time management skills enable prioritization, focus, and efficiency, balancing responsibilities, leisure, and personal development for productive and fulfilling lives.",
  "Traveling by train allows one to witness landscapes, towns, and people passing by, offering reflection time and inspiration during long journeys.",
  "Sports teach discipline, teamwork, strategy, and resilience, while providing exercise, competition, and fun, building character and physical fitness simultaneously.",
  "Photography captures moments, stories, and emotions, preserving memories and perspectives that might otherwise be forgotten, while stimulating creativity and visual appreciation.",
  "Volunteering benefits communities, fosters empathy, builds skills, and provides a sense of purpose, contributing to positive social change and personal growth.",
  "Artificial intelligence and machine learning are transforming industries, automating tasks, analyzing data, and providing insights that drive decisions and efficiency across sectors.",
  "Cooking requires creativity, precision, and patience, combining ingredients to produce flavors and dishes that nourish, delight, and bring people together around meals.",
  "Learning to code requires logic, problem-solving, patience, and practice, gradually building skills that open doors to software development careers and creative projects.",
  "Mindful breathing techniques help calm the mind, reduce anxiety, and enhance focus, allowing for better decision-making and emotional regulation.",
  "Financial literacy enables individuals to manage money effectively, budget wisely, invest strategically, and plan for future goals with confidence.",
  "Public speaking skills empower individuals to communicate ideas clearly, influence audiences, and inspire action while building confidence and presence.",
  "Exploring nature trails encourages curiosity, observation, and physical activity, connecting individuals to the outdoors and promoting wellness.",
  "Writing daily enhances communication, creativity, and critical thinking, helping articulate ideas, express emotions, and record experiences over time.",
  "Social media connects people globally, providing communication, information, entertainment, and networking opportunities, while requiring mindful usage to avoid distraction and stress.",
  "Problem-solving skills develop through practice, analysis, and persistence, enabling individuals to overcome challenges and find effective, efficient solutions.",
  "Yoga promotes flexibility, strength, relaxation, and mindfulness, improving overall physical and mental well-being through regular practice.",
  "Reading history provides insights into past civilizations, events, and human behavior, shaping understanding and guiding future decisions.",
  "Technology and creativity combine to produce innovative solutions, applications, and art that enhance human experiences and solve complex problems.",
  "Collaboration leverages diverse perspectives, skills, and experiences to achieve goals and innovate beyond what individuals can accomplish alone.",
  "Effective note-taking enhances learning, retention, and understanding, organizing information clearly for study, reflection, and recall.",
  "Critical thinking involves analyzing, evaluating, and synthesizing information to make reasoned judgments and informed decisions in complex situations.",
  "Consistent practice in any skill leads to improvement, mastery, and confidence, reinforcing knowledge and abilities over time.",
  "Digital security protects personal, financial, and professional information, requiring awareness, strong passwords, and safe practices online.",
  "Adaptability allows individuals to respond to change, learn new skills, and thrive in dynamic environments personally and professionally.",
  "Mindset shapes actions, resilience, and outcomes, with positive, growth-oriented thinking fostering success, learning, and fulfillment.",
  "Collaboration in remote teams requires communication, trust, and coordination, utilizing technology and structured processes to achieve goals efficiently.",
  "Exercise improves cardiovascular health, strength, flexibility, and mood, supporting overall well-being and longevity through regular physical activity.",
  "Mentorship provides guidance, knowledge, and support, helping mentees grow professionally, personally, and intellectually through shared experience and advice.",
];
